# Generated by Django 5.0.6 on 2024-06-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_project_tag_project_lat_project_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='lng',
            new_name='lang',
        ),
    ]
