# Generated by Django 5.0.6 on 2024-06-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_category_city_region_subcategory_city_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
