# Generated by Django 5.0.6 on 2024-06-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_member_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
    ]
