# Generated by Django 5.0.6 on 2024-06-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_company_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='category',
        ),
        migrations.AddField(
            model_name='company',
            name='categories',
            field=models.ManyToManyField(related_name='companies', to='dashboard.category'),
        ),
    ]
