# Generated by Django 5.0.6 on 2024-06-12 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_company_category_company_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='dashboard.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyPhoneNumber',
            field=models.CharField(max_length=20),
        ),
    ]
