# Generated by Django 5.0.6 on 2024-06-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_company_categories_category_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='CompanyName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyPhoneNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
