# Generated by Django 5.0.6 on 2024-06-27 16:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_projectimage_project_tab_projectfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='tab',
        ),
        migrations.RemoveField(
            model_name='projectfile',
            name='tab',
        ),
        migrations.AddField(
            model_name='projectfile',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectimage',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('reperage', 'Reperage'), ('maquette', 'Maquette'), ('dessins_technique', 'Dessins Technique'), ('simulation', 'Simulation'), ('realisation', 'Realisation')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='dashboard.project')),
            ],
            options={
                'unique_together': {('project', 'stage')},
            },
        ),
        migrations.AddField(
            model_name='projectfile',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dashboard.projectstage'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.projectstage'),
        ),
        migrations.DeleteModel(
            name='Tab',
        ),
    ]
