# Generated by Django 5.0.6 on 2024-06-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_projectimage_tab_remove_projectfile_tab_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='name',
            new_name='info',
        ),
        migrations.RemoveField(
            model_name='projectfile',
            name='name',
        ),
    ]
