# Generated by Django 5.0.6 on 2024-07-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_project_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
