# Generated by Django 5.0.6 on 2024-07-02 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_remove_projectimagecomment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimagecomment',
            name='user_name',
        ),
        migrations.AddField(
            model_name='projectimagecomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
