# Generated by Django 5.0.6 on 2024-07-02 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_remove_projectimagecomment_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimagecomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
