# Generated by Django 5.0.6 on 2024-07-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_projectimagecomment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='project',
            name='lat',
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
