# Generated by Django 5.0.6 on 2024-07-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_comment_file_comment_image_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subportal',
            name='portal',
        ),
        migrations.DeleteModel(
            name='Portal',
        ),
        migrations.DeleteModel(
            name='SubPortal',
        ),
    ]
